### PR TITLE
Feature/bump deps

### PR DESCRIPTION
**Pull request by alan-agius4**
test(glob-base): fix invalid glob pattern	
feat(dependencies): bump `glob-parent`, `is-glob` and `should`

### CODE REVIEW

**Comment by pravi** [comment]
@alan-agius4 can you try to update the pr with is-glob 4.0?

**Comment by alan-agius4** [comment]
one of the test will fail 
```
globBase('?').should.eql({ base: '.', isGlob: true, glob: '?' });
```

**Comment by pravi** [comment]
With is-glob 4.0, this test fails.

```
1) glob-base: qmarks::

      AssertionError: expected Object { base: '.', glob: '?', isGlob: false } to equal Object { base: '.', glob: '?', isGlob: true } (at isGlob, A has false and B has true)
      + expected - actual

       {
         "base": ".",
         "glob": "?",
      -  "isGlob": false
      +  "isGlob": true
       }
      
      at Assertion.fail (/usr/lib/nodejs/should/lib/assertion.js:92:17)
      at Assertion.value (/usr/lib/nodejs/should/lib/assertion.js:164:19)
      at Context.<anonymous> (/home/pravi/forge/debian/git/pkg-javascript/node-glob-base/test.js:129:26)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:223:21)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:216:7)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:373:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:451:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:298:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:308:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:246:23)
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)
  
```

**Comment by alan-agius4** [comment]
is `?` only a valid glob?, 

Anyways it seems that this package, is not maintained any longer.

**Comment by pravi** [comment]
it seems valid on the unix shell.
```
pravi@nishumbha:/tmp/test$ ls
pravi@nishumbha:/tmp/test$ ls ?
ls: cannot access '?': No such file or directory
pravi@nishumbha:/tmp/test$ touch a
pravi@nishumbha:/tmp/test$ ls ?
a
pravi@nishumbha:/tmp/test$ 
```

**Comment by pravi** [comment]
@jonschlinkert how to proceed here?

**Comment by jonschlinkert** [comment]
@pravi I'm thinking that `?` should be considered a valid path character by default, and not a glob. We could make this optional. Thoughts?

**Comment by pravi** [comment]
Coming from shell background, I think following the shell behaviour would be good ie, make ? glob by default. But your call.

**Comment by necessary129** [comment]
Python accepts `?` as a standalone glob pattern:

```
In [1]: from fnmatch import fnmatch

In [2]: fnmatch('a','?')
Out[2]: True

In [3]: fnmatch('ab','?')
Out[3]: False

In [4]: from glob import glob

In [5]: glob('/home/shamil/?')
Out[5]: ['/home/shamil/0', '/home/shamil/1', '/home/shamil/o', '/home/shamil/a']

In [6]: glob('?')
Out[6]: ['0', '1', 'o', 'a']
```

**Comment by necessary129** [comment]
[XCU specification, Section 2.13, Pattern Matching Notation](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_13) of the UNIX specification says:

> [...] If any character (ordinary, shell special, or pattern special) is quoted, that pattern shall match the character itself. **The shell special characters always require quoting.**

So it can be safe to say that a single `?` should be taken as a glob?

**Pull request closed without merging**
